config/routes.rb
PizzaDelivery::Application.routes.draw do
  get "sessions/new"
  root 'drivers#index'

  resource :sessions, only: [:new, :create, :destroy]

  resources :drivers do
    resources :availabilities
  end

end

app/models/availability.rb
class Availability
  include Mongoid::Document
  field :day_of_week, type: Integer
  field :start_hour, type: Integer
  field :end_hour, type: Integer

  belongs_to :driver
end

app/models/driver.rb
require "bcrypt"

class Driver
  include Mongoid::Document
  field :name, type: String
  field :email, type: String
  field :password_digest, type: String

  has_many :availabilities

  accepts_nested_attributes_for :availabilities

  def password
    @password
  end

  def password=(new_password)
    @password = new_password
    self.password_digest = BCrypt::Password.create(new_password)
  end

  def authenticate(test_password)
    if BCrypt::Password.new(self.password_digest) == test_password
      self
    else
      false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :hour_friendly

  include ApplicationHelper

  def authenticate_user
    if !self.current_user
      redirect_to new_sessions_path
    end
  end

end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  before_action :set_driver

  def index
    @availabilities = @driver.availabilities
  end

  def new
    @availability = Availability.new
  end

  def create
    @driver.availabilities.create(availability_params)
    redirect_to driver_availabilities_path(@driver)
  end

  def edit
    @availability = Availability.find(params[:id])
  end

  def update
    a = Availability.find(params[:id])
    a.update(availability_params)
    redirect_to driver_availabilities_path(@driver)
  end

  def destroy
    a = Availability.find(params[:id])
    a.destroy
    redirect_to driver_availabilities_path(@driver)
  end

private
  def availability_params
    params.require(:availability).permit(:day_of_week, :start_hour, :end_hour)
  end

  def set_driver
    @driver = Driver.find(params[:driver_id])
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
    # The .order("name ASC") shows all the drivers by name, ascending
  	@drivers = Driver.all.order("name ASC")
  end

  def new
  	@driver = Driver.new
    # In order to show an empty availability that can be modified,
    # we build this one in memory only
    @driver.availabilities.build
  end

  def create
  	Driver.create(driver_params)
  	redirect_to drivers_path
  end

  def edit
  	@driver = Driver.find(params[:id])
  end

  def update
    d = Driver.find(params[:id])
  	d.update(driver_params)
  	redirect_to driver_availabilities_path(d)
  end

  def destroy
    d = Driver.find(params[:id])
    d.destroy
  	redirect_to drivers_path
  end

private
	def driver_params
		params.require(:driver).permit(:name, :email, :password,
      # These availabilities_attributes are because we had an
      # accepts_nested_attributes_for :availabilities back in the
      # Driver model
     availabilities_attributes: [:id, :day_of_week, :start_hour, :end_hour])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = Driver.where(:email => params[:session][:email]).first

    if @user == nil || !@user.authenticate(params[:session][:password])
      flash[:error] = "Invalid email/password combination"
      render 'new'
    else
      session[:remember_token] = @user.id
      @current_user = @user
      redirect_to drivers_path
    end

  end

  def destroy
    session.delete(:remember_token)
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= session[:remember_token] && Driver.find(session[:remember_token])
  end

	def hour_friendly(hourNum)
		ret = hourNum % 12
		(ret == 0 ? "12" : ret.to_s) + ((hourNum % 24) < 12 ? "AM" : "PM")
	end

	# These are used in the _availability partial
	def day_array(add_pick)
		ret = (0..6).map {|num| [Date::DAYNAMES[num], num]}
		ret.unshift(["<< Pick >>",nil]) if add_pick
		ret
	end
	def hour_array(add_pick)
		ret = (11..27).map {|num| [hour_friendly(num), num]}
		ret.unshift(["<< >>",nil]) if add_pick
		ret
	end
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/availabilities/_form.html.erb
<%= form_for [@driver, @availability] do |f| %>
	<div class="availabilityDropdowns">
		<%= f.select :day_of_week, day_array(f.object.new_record?), {}, {class: "dayDropDown"} %>
		<%= f.select :start_hour, hour_array(f.object.new_record?) %> -
		<%= f.select :end_hour, hour_array(f.object.new_record?) %>
		<% if !f.object.new_record? %>
			<%= link_to "X", driver_availability_path(@driver, f.object.id), {method: :delete} %>
		<% end %>
	</div>
	<%= f.submit %>
<% end %>

app/views/availabilities/edit.html.erb
<h1>Availabilities#edit</h1>

Edit an availability for ...

<%= render 'form' %>

app/views/availabilities/index.html.erb
<h1>Availabilities for <%= @driver.name %></h1>

<ul>
<% @availabilities.each do |a| %>
	<li>
		<%= link_to edit_driver_availability_path(@driver, a) do %>
			<%= Date::DAYNAMES[a.day_of_week] %>,
			<%= hour_friendly(a.start_hour) %> - <%= hour_friendly(a.end_hour) %>
		<% end %>
	</li>
<% end %>
</ul>

<%= link_to "add a new availability", new_driver_availability_path(@driver) %>

app/views/availabilities/new.html.erb
<h1>Availabilities#new</h1>

Add an availability to a driver<br />
<br />
<%= render "form" %>

app/views/drivers/_form.html.erb
<%= form_for @driver do |f| %>
	Name: <%= f.text_field :name %>
	Email: <%= f.text_field :email %>
	Password: <%= f.password_field :password %>
	<br />

		<!-- Let's put the fields for availabilities here -->
		<%= f.fields_for :availabilities do |builder| %>
				<%= builder.select :day_of_week, day_array(builder.object.new_record?), {}, {class: "dayDropDown"} %>
			<%= builder.select :start_hour, hour_array(builder.object.new_record?) %> -
			<%= builder.select :end_hour, hour_array(builder.object.new_record?) %>
			<% if !builder.object.new_record? %>
				<%= link_to "X", driver_availability_path(@driver, builder.object.id), {method: :delete} %>
			<% end %>
			<br />
		<% end %>

	<%= f.submit %>
<% end %>

app/views/drivers/edit.html.erb
<h1>Drivers#edit</h1>

<%= render 'form' %>

app/views/drivers/index.html.erb
<h1>Drivers#index</h1>

<ul>
<% @drivers.each do |d| %>
	<li>
		<%= link_to d.name, edit_driver_path(d) %>
		<%= link_to "Availabilities", driver_availabilities_path(d) %>
	</li>
<% end %>
</ul>

app/views/drivers/new.html.erb
Tell me about your new driver<br />
<br />
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PizzaDelivery</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if !current_user %>
  <%= link_to "Sign Up", new_driver_path %>
  <%= link_to "Log In", new_sessions_path %>
<% else %>
  Hello, <%= current_user.name %>
  <%= link_to "Log Out", sessions_path, :method => :delete %>
<% end %>

<hr />

<%= yield %>

</body>
</html>